### ISSUE TITLE
支持部署到cloudflare上吗

### ISSUE THREAD

**Issue by 2328760190** [patchescamerababy/ChatOn2API#1]
这个能部署到cf上么，或者大佬给个docker会更方便一点。谢谢

**Comment by patchescamerababy** [comment]
刚在Linux.do上看见

你说的部署到cf是指部署到Workers/Pages，无需服务器吗？Demo目前用Pages转发至服务器

用Python可简易搭建，无需舍近求远。考虑到各种因素，未放出Token算法

**Comment by 2328760190** [comment]
有服务器能自己部署吗，还是说只有个demo能用

**Comment by patchescamerababy** [comment]
可以部署在服务器上，也可本地跑。但本地跑不可传Base64图片，可传URL直链

**Comment by 2328760190** [comment]
不是没给bearer的代码吗
